<?php
return [
    "CPF" => env('INC1_CSV_CPF', 'field_24515'),
    "SEXO" => env('INC1_CSV_SEXO', 'field_24502'),
    "FLAG_CAD_ESTADUAL" => env('INC1_CSV_FLAG_CAD_ESTADUAL', '1'),
    "FLAG_CAD_MUNICIPAL" => env('INC1_CSV_FLAG_CAD_MUNICIPAL', '0'),
    "FLAG_CAD_DISTRITAL" => env('INC1_CSV_FLAG_CAD_DISTRITAL', '0'),
    "FLAG_CAD_SNIIC" => env('INC1_CSV_FLAG_CAD_SNIIC', '0'),
    "FLAG_CAD_SALIC" => env('INC1_CSV_FLAG_CAD_SALIC', '0'),
    "FLAG_CAD_SICAB" => env('INC1_CSV_FLAG_CAD_SICAB', '0'),
    "FLAG_CAD_OUTROS" => env('INC1_CSV_FLAG_CAD_OUTROS', '0'),
    "SISTEMA_CAD_OUTROS" => env('INC1_CSV_SISTEMA_CAD_OUTROS', null),
    "IDENTIFICADOR_CAD_OUTROS" => env('INC1_CSV_IDENTIFICADOR_CAD_OUTROS', null),
    "FLAG_ATUACAO_ARTES_CENICAS" => env('INC1_CSV_FLAG_ATUACAO_ARTES_CENICAS', 'field_24496'),
    "FLAG_ATUACAO_AUDIOVISUAL" => env('INC1_CSV_FLAG_ATUACAO_AUDIOVISUAL', 'field_24496'),
    "FLAG_ATUACAO_MUSICA" => env('INC1_CSV_FLAG_ATUACAO_MUSICA', 'field_24496'),
    "FLAG_ATUACAO_ARTES_VISUAIS" => env('INC1_CSV_FLAG_ATUACAO_ARTES_VISUAIS', 'field_24496'),
    "FLAG_ATUACAO_PATRIMONIO_CULTURAL" => env('INC1_CSV_FLAG_ATUACAO_PATRIMONIO_CULTURAL', 'field_24496'),
    "FLAG_ATUACAO_MUSEUS_MEMORIA" => env('INC1_CSV_FLAG_ATUACAO_MUSEUS_MEMORIA', 'field_24496'),
    "FLAG_ATUACAO_HUMANIDADES" => env('INC1_CSV_FLAG_ATUACAO_HUMANIDADES', 'field_24496'),
    "FAMILIARCPF" => env('INC1_CSV_FAMILIARCPF','field_24500'),
    "GRAUPARENTESCO" => env('INC1_CSV_GRAUPARENTESCO','field_24500'),
    "parameters_csv_default" => [
        "status" => ''
    ],
    'atuacoes-culturais' => [ // Opções para área de atuações culturais
        'artes-cenicas' => [],
        'audiovisual' => [],
        'musica' => [],
        'artes-visuais' => [],
        'patrimonio-cultural' => [],
        'museu-memoria' => [],
        'humanidades' => [],
    ],
];
